### ISSUE TITLE
1- add asset folllow the exact things in video

### ISSUE THREAD

**Issue by artmarydotir** [mah9372mgh/vue#1]
- add asset folder
- do not add another image. (https://img.freepik.com/free-photo/beautiful-single-isolated-pink-rose-white_181624-25682.jpg?w=826&t=st=1688814982~exp=1688815582~hmac=69dd3bebae02ccf61025cf23cadd15b85322cb7c113f14528cfcc0890fa77d46')

the goal is go along with the video challenge. not the things we like. :)

**Comment by mah9372mgh** [comment]
Done!
